
ENZYMES = {'AfeI': 'AGC*GCT',
           'AluI': 'AG*CT',
           'BamHI': 'G*GATCC',
           'BalI': 'TGG*CCA',
           'BglII': 'A*GATCT',
           'ClaI': 'AT*CGAT',
           'EcoRI': 'G*AATTC',
           'EcoRV': 'GAT*ATC',
           'HaeIII': 'GG*CC',
           'HindIII': 'A*AGCTT',
           'KpnI': 'GGTAC*C',
           'NotI': 'GC*GGCCGC',
           'PstI': 'GTGCA*G',
           'SalI': 'G*TCGAC',
           'SmaI': 'CCC*GGG',
           'StuI': 'AGC*CCT',
           'TaqI': 'T*CGA',
           'XbaI': 'T*CTAGA',
           'XmaI': 'C*CCGGG'}
